### ISSUE TITLE
bot is crashing when running with a config file

### ISSUE THREAD

**Issue by M0UL** [subzero79/docker-telegram-sonarr-bot#2]
the bot keeps crashing when running with a config file. it cashed after finding the config file.

log; http://pastebin.com/ZBqKp4rZ

**Comment by subzero79** [comment]
New code has been committed to the original node application, I'll review it tomorrow so I can update the image.
Unfortunately is an automated build so new code in onedrop repo pushes a new image build, so it tends to break frequently

**Comment by subzero79** [comment]
I cannot reproduce this, do you have sonarr with password/ssl?

**Comment by M0UL** [comment]
i dont use sonarr with a password of ssl.

i am running the docker image on a synology

**Comment by subzero79** [comment]
Could be a syntax error in your config.json. Check it again that it doesn't have a missing double quotes or comma missing.

**Comment by M0UL** [comment]
i will check it again

edit: check it and found nothing wrong with it

**Comment by subzero79** [comment]
If you edit your comments i don't get a notification.

**Comment by subzero79** [comment]
If you want you can send me in irc your full config.json as dropbox link to download.

**Comment by M0UL** [comment]
i have done this a few days ago

**Comment by subzero79** [comment]
So is working for you now?

**Comment by M0UL** [comment]
nope

**Comment by subzero79** [comment]
There is an email in my github. Send me your config file in a Dropbox link if you want.

**Comment by M0UL** [comment]
the email on your profile page does not work
